/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MangaDex.Client;
using MangaDex.Api;
// uncomment below to import models
//using MangaDex.Model;

namespace MangaDex.Test.Api
{
    /// <summary>
    ///  Class for testing FollowsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FollowsApiTests : IDisposable
    {
        private FollowsApi instance;

        public FollowsApiTests()
        {
            instance = new FollowsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FollowsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FollowsApi
            //Assert.IsType<FollowsApi>(instance);
        }

        /// <summary>
        /// Test GetUserFollowsGroup
        /// </summary>
        [Fact]
        public void GetUserFollowsGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //List<string> includes = null;
            //var response = instance.GetUserFollowsGroup(limit, offset, includes);
            //Assert.IsType<ScanlationGroupList>(response);
        }

        /// <summary>
        /// Test GetUserFollowsGroupId
        /// </summary>
        [Fact]
        public void GetUserFollowsGroupIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetUserFollowsGroupId(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test GetUserFollowsList
        /// </summary>
        [Fact]
        public void GetUserFollowsListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //var response = instance.GetUserFollowsList(limit, offset);
            //Assert.IsType<CustomListList>(response);
        }

        /// <summary>
        /// Test GetUserFollowsListId
        /// </summary>
        [Fact]
        public void GetUserFollowsListIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetUserFollowsListId(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test GetUserFollowsManga
        /// </summary>
        [Fact]
        public void GetUserFollowsMangaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //List<string> includes = null;
            //var response = instance.GetUserFollowsManga(limit, offset, includes);
            //Assert.IsType<MangaList>(response);
        }

        /// <summary>
        /// Test GetUserFollowsMangaId
        /// </summary>
        [Fact]
        public void GetUserFollowsMangaIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetUserFollowsMangaId(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test GetUserFollowsUser
        /// </summary>
        [Fact]
        public void GetUserFollowsUserTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //var response = instance.GetUserFollowsUser(limit, offset);
            //Assert.IsType<UserList>(response);
        }

        /// <summary>
        /// Test GetUserFollowsUserId
        /// </summary>
        [Fact]
        public void GetUserFollowsUserIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetUserFollowsUserId(id);
            //Assert.IsType<Response>(response);
        }
    }
}
