/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MangaDex.Client;
using MangaDex.Api;
// uncomment below to import models
//using MangaDex.Model;

namespace MangaDex.Test.Api
{
    /// <summary>
    ///  Class for testing ReadMarkerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReadMarkerApiTests : IDisposable
    {
        private ReadMarkerApi instance;

        public ReadMarkerApiTests()
        {
            instance = new ReadMarkerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReadMarkerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReadMarkerApi
            //Assert.IsType<ReadMarkerApi>(instance);
        }

        /// <summary>
        /// Test GetMangaChapterReadmarkers
        /// </summary>
        [Fact]
        public void GetMangaChapterReadmarkersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.GetMangaChapterReadmarkers(id);
            //Assert.IsType<GetMangaChapterReadmarkers200Response>(response);
        }

        /// <summary>
        /// Test GetMangaChapterReadmarkers2
        /// </summary>
        [Fact]
        public void GetMangaChapterReadmarkers2Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> ids = null;
            //bool? grouped = null;
            //var response = instance.GetMangaChapterReadmarkers2(ids, grouped);
            //Assert.IsType<GetMangaChapterReadmarkers2200Response>(response);
        }

        /// <summary>
        /// Test GetReadingHistory
        /// </summary>
        [Fact]
        public void GetReadingHistoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetReadingHistory();
            //Assert.IsType<GetReadingHistory200Response>(response);
        }

        /// <summary>
        /// Test PostMangaChapterReadmarkers
        /// </summary>
        [Fact]
        public void PostMangaChapterReadmarkersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //bool? updateHistory = null;
            //ChapterReadMarkerBatch chapterReadMarkerBatch = null;
            //var response = instance.PostMangaChapterReadmarkers(id, updateHistory, chapterReadMarkerBatch);
            //Assert.IsType<FollowListId200Response>(response);
        }
    }
}
