/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MangaDex.Client;
using MangaDex.Api;
// uncomment below to import models
//using MangaDex.Model;

namespace MangaDex.Test.Api
{
    /// <summary>
    ///  Class for testing ReportApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReportApiTests : IDisposable
    {
        private ReportApi instance;

        public ReportApiTests()
        {
            instance = new ReportApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReportApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReportApi
            //Assert.IsType<ReportApi>(instance);
        }

        /// <summary>
        /// Test GetReportReasonsByCategory
        /// </summary>
        [Fact]
        public void GetReportReasonsByCategoryTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string category = null;
            //var response = instance.GetReportReasonsByCategory(category);
            //Assert.IsType<GetReportReasonsByCategory200Response>(response);
        }

        /// <summary>
        /// Test GetReports
        /// </summary>
        [Fact]
        public void GetReportsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //string category = null;
            //Guid? reasonId = null;
            //Guid? objectId = null;
            //string status = null;
            //GetReportsOrderParameter order = null;
            //List<string> includes = null;
            //var response = instance.GetReports(limit, offset, category, reasonId, objectId, status, order, includes);
            //Assert.IsType<ReportListResponse>(response);
        }

        /// <summary>
        /// Test PostReport
        /// </summary>
        [Fact]
        public void PostReportTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contentType = null;
            //PostReportRequest postReportRequest = null;
            //var response = instance.PostReport(contentType, postReportRequest);
            //Assert.IsType<Response>(response);
        }
    }
}
