/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MangaDex.Client;
using MangaDex.Api;
// uncomment below to import models
//using MangaDex.Model;

namespace MangaDex.Test.Api
{
    /// <summary>
    ///  Class for testing ScanlationGroupApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ScanlationGroupApiTests : IDisposable
    {
        private ScanlationGroupApi instance;

        public ScanlationGroupApiTests()
        {
            instance = new ScanlationGroupApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScanlationGroupApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ScanlationGroupApi
            //Assert.IsType<ScanlationGroupApi>(instance);
        }

        /// <summary>
        /// Test DeleteGroupId
        /// </summary>
        [Fact]
        public void DeleteGroupIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.DeleteGroupId(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test DeleteGroupIdFollow
        /// </summary>
        [Fact]
        public void DeleteGroupIdFollowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.DeleteGroupIdFollow(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test GetGroupId
        /// </summary>
        [Fact]
        public void GetGroupIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //List<string> includes = null;
            //var response = instance.GetGroupId(id, includes);
            //Assert.IsType<ScanlationGroupResponse>(response);
        }

        /// <summary>
        /// Test GetSearchGroup
        /// </summary>
        [Fact]
        public void GetSearchGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //int? offset = null;
            //List<Guid> ids = null;
            //string name = null;
            //string focusedLanguage = null;
            //List<string> includes = null;
            //GetSearchGroupOrderParameter order = null;
            //var response = instance.GetSearchGroup(limit, offset, ids, name, focusedLanguage, includes, order);
            //Assert.IsType<ScanlationGroupList>(response);
        }

        /// <summary>
        /// Test PostGroup
        /// </summary>
        [Fact]
        public void PostGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string contentType = null;
            //CreateScanlationGroup createScanlationGroup = null;
            //var response = instance.PostGroup(contentType, createScanlationGroup);
            //Assert.IsType<ScanlationGroupResponse>(response);
        }

        /// <summary>
        /// Test PostGroupIdFollow
        /// </summary>
        [Fact]
        public void PostGroupIdFollowTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //var response = instance.PostGroupIdFollow(id);
            //Assert.IsType<Response>(response);
        }

        /// <summary>
        /// Test PutGroupId
        /// </summary>
        [Fact]
        public void PutGroupIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid id = null;
            //string contentType = null;
            //ScanlationGroupEdit scanlationGroupEdit = null;
            //var response = instance.PutGroupId(id, contentType, scanlationGroupEdit);
            //Assert.IsType<ScanlationGroupResponse>(response);
        }
    }
}
