/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MangaDex.Client;
using MangaDex.Api;
// uncomment below to import models
//using MangaDex.Model;

namespace MangaDex.Test.Api
{
    /// <summary>
    ///  Class for testing StatisticsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class StatisticsApiTests : IDisposable
    {
        private StatisticsApi instance;

        public StatisticsApiTests()
        {
            instance = new StatisticsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatisticsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' StatisticsApi
            //Assert.IsType<StatisticsApi>(instance);
        }

        /// <summary>
        /// Test GetStatisticsChapterUuid
        /// </summary>
        [Fact]
        public void GetStatisticsChapterUuidTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //var response = instance.GetStatisticsChapterUuid(uuid);
            //Assert.IsType<GetStatisticsChapterUuid200Response>(response);
        }

        /// <summary>
        /// Test GetStatisticsChapters
        /// </summary>
        [Fact]
        public void GetStatisticsChaptersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> chapter = null;
            //var response = instance.GetStatisticsChapters(chapter);
            //Assert.IsType<GetStatisticsChapterUuid200Response>(response);
        }

        /// <summary>
        /// Test GetStatisticsGroupUuid
        /// </summary>
        [Fact]
        public void GetStatisticsGroupUuidTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //var response = instance.GetStatisticsGroupUuid(uuid);
            //Assert.IsType<GetStatisticsChapterUuid200Response>(response);
        }

        /// <summary>
        /// Test GetStatisticsGroups
        /// </summary>
        [Fact]
        public void GetStatisticsGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> group = null;
            //var response = instance.GetStatisticsGroups(group);
            //Assert.IsType<GetStatisticsChapterUuid200Response>(response);
        }

        /// <summary>
        /// Test GetStatisticsManga
        /// </summary>
        [Fact]
        public void GetStatisticsMangaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //List<Guid> manga = null;
            //var response = instance.GetStatisticsManga(manga);
            //Assert.IsType<GetStatisticsManga200Response>(response);
        }

        /// <summary>
        /// Test GetStatisticsMangaUuid
        /// </summary>
        [Fact]
        public void GetStatisticsMangaUuidTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //var response = instance.GetStatisticsMangaUuid(uuid);
            //Assert.IsType<GetStatisticsMangaUuid200Response>(response);
        }
    }
}
