/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MangaDex.Model;
using MangaDex.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MangaDex.Test.Model
{
    /// <summary>
    ///  Class for testing ChapterAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ChapterAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ChapterAttributes
        //private ChapterAttributes instance;

        public ChapterAttributesTests()
        {
            // TODO uncomment below to create an instance of ChapterAttributes
            //instance = new ChapterAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ChapterAttributes
        /// </summary>
        [Fact]
        public void ChapterAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" ChapterAttributes
            //Assert.IsType<ChapterAttributes>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Volume'
        /// </summary>
        [Fact]
        public void VolumeTest()
        {
            // TODO unit test for the property 'Volume'
        }

        /// <summary>
        /// Test the property 'Chapter'
        /// </summary>
        [Fact]
        public void ChapterTest()
        {
            // TODO unit test for the property 'Chapter'
        }

        /// <summary>
        /// Test the property 'Pages'
        /// </summary>
        [Fact]
        public void PagesTest()
        {
            // TODO unit test for the property 'Pages'
        }

        /// <summary>
        /// Test the property 'TranslatedLanguage'
        /// </summary>
        [Fact]
        public void TranslatedLanguageTest()
        {
            // TODO unit test for the property 'TranslatedLanguage'
        }

        /// <summary>
        /// Test the property 'Uploader'
        /// </summary>
        [Fact]
        public void UploaderTest()
        {
            // TODO unit test for the property 'Uploader'
        }

        /// <summary>
        /// Test the property 'ExternalUrl'
        /// </summary>
        [Fact]
        public void ExternalUrlTest()
        {
            // TODO unit test for the property 'ExternalUrl'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }

        /// <summary>
        /// Test the property 'PublishAt'
        /// </summary>
        [Fact]
        public void PublishAtTest()
        {
            // TODO unit test for the property 'PublishAt'
        }

        /// <summary>
        /// Test the property 'ReadableAt'
        /// </summary>
        [Fact]
        public void ReadableAtTest()
        {
            // TODO unit test for the property 'ReadableAt'
        }
    }
}
