/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Text.Json;
using System.Text.Json.Serialization;
using MangaDex.Client;

namespace MangaDex.Model
{
    /// <summary>
    ///  Abstract base class for oneOf, anyOf schemas in the OpenAPI specification
    /// </summary>
    public abstract partial class AbstractOpenAPISchema
    {
        /// <summary>
        ///  Custom JSON serializer. Unknown members are disallowed so that oneOf/anyOf
        ///  candidate types only match when the payload maps exactly, mirroring the previous
        ///  Newtonsoft <c>MissingMemberHandling.Error</c> behaviour.
        /// </summary>
        static public readonly JsonSerializerOptions SerializerSettings = BuildStrictOptions();

        /// <summary>
        ///  Custom JSON serializer for objects with additional properties (unknown members ignored).
        /// </summary>
        static public readonly JsonSerializerOptions AdditionalPropertiesSerializerSettings = BuildLenientOptions();

        private static JsonSerializerOptions BuildStrictOptions()
        {
            // No AllowReadingFromString: keeps oneOf/anyOf candidates mutually exclusive by JSON
            // shape (e.g. a quoted number must not also match an `int` candidate).
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                UnmappedMemberHandling = JsonUnmappedMemberHandling.Disallow
            };
            options.Converters.Add(new StringEnumMemberConverter());
            return options;
        }

        private static JsonSerializerOptions BuildLenientOptions()
        {
            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                NumberHandling = JsonNumberHandling.AllowReadingFromString
            };
            options.Converters.Add(new StringEnumMemberConverter());
            return options;
        }

        /// <summary>
        /// Gets or Sets the actual instance
        /// </summary>
        public abstract Object ActualInstance { get; set; }

        /// <summary>
        /// Gets or Sets IsNullable to indicate whether the instance is nullable
        /// </summary>
        public bool IsNullable { get; protected set; }

        /// <summary>
        /// Gets or Sets the schema type, which can be either `oneOf` or `anyOf`
        /// </summary>
        public string SchemaType { get; protected set; }

        /// <summary>
        /// Converts the instance into JSON string.
        /// </summary>
        public abstract string ToJson();
    }
}
