/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaDex.Client.OpenAPIDateConverter;

namespace MangaDex.Model
{
    /// <summary>
    /// AuthorAttributes
    /// </summary>
    [DataContract(Name = "AuthorAttributes")]
    public partial class AuthorAttributes : IEquatable<AuthorAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorAttributes" /> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="imageUrl">imageUrl.</param>
        /// <param name="biography">biography.</param>
        /// <param name="twitter">twitter.</param>
        /// <param name="pixiv">pixiv.</param>
        /// <param name="melonBook">melonBook.</param>
        /// <param name="fanBox">fanBox.</param>
        /// <param name="booth">booth.</param>
        /// <param name="nicoVideo">nicoVideo.</param>
        /// <param name="skeb">skeb.</param>
        /// <param name="fantia">fantia.</param>
        /// <param name="tumblr">tumblr.</param>
        /// <param name="youtube">youtube.</param>
        /// <param name="weibo">weibo.</param>
        /// <param name="naver">naver.</param>
        /// <param name="website">website.</param>
        /// <param name="varVersion">varVersion.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="updatedAt">updatedAt.</param>
        public AuthorAttributes(string name = default(string), string imageUrl = default(string), Dictionary<string, string> biography = default(Dictionary<string, string>), string twitter = default(string), string pixiv = default(string), string melonBook = default(string), string fanBox = default(string), string booth = default(string), string nicoVideo = default(string), string skeb = default(string), string fantia = default(string), string tumblr = default(string), string youtube = default(string), string weibo = default(string), string naver = default(string), string website = default(string), int varVersion = default(int), string createdAt = default(string), string updatedAt = default(string))
        {
            this.Name = name;
            this.ImageUrl = imageUrl;
            this.Biography = biography;
            this.Twitter = twitter;
            this.Pixiv = pixiv;
            this.MelonBook = melonBook;
            this.FanBox = fanBox;
            this.Booth = booth;
            this.NicoVideo = nicoVideo;
            this.Skeb = skeb;
            this.Fantia = fantia;
            this.Tumblr = tumblr;
            this.Youtube = youtube;
            this.Weibo = weibo;
            this.Naver = naver;
            this.Website = website;
            this.VarVersion = varVersion;
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
        }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets ImageUrl
        /// </summary>
        [DataMember(Name = "imageUrl", EmitDefaultValue = true)]
        public string ImageUrl { get; set; }

        /// <summary>
        /// Gets or Sets Biography
        /// </summary>
        [DataMember(Name = "biography", EmitDefaultValue = false)]
        public Dictionary<string, string> Biography { get; set; }

        /// <summary>
        /// Gets or Sets Twitter
        /// </summary>
        [DataMember(Name = "twitter", EmitDefaultValue = true)]
        public string Twitter { get; set; }

        /// <summary>
        /// Gets or Sets Pixiv
        /// </summary>
        [DataMember(Name = "pixiv", EmitDefaultValue = true)]
        public string Pixiv { get; set; }

        /// <summary>
        /// Gets or Sets MelonBook
        /// </summary>
        [DataMember(Name = "melonBook", EmitDefaultValue = true)]
        public string MelonBook { get; set; }

        /// <summary>
        /// Gets or Sets FanBox
        /// </summary>
        [DataMember(Name = "fanBox", EmitDefaultValue = true)]
        public string FanBox { get; set; }

        /// <summary>
        /// Gets or Sets Booth
        /// </summary>
        [DataMember(Name = "booth", EmitDefaultValue = true)]
        public string Booth { get; set; }

        /// <summary>
        /// Gets or Sets NicoVideo
        /// </summary>
        [DataMember(Name = "nicoVideo", EmitDefaultValue = true)]
        public string NicoVideo { get; set; }

        /// <summary>
        /// Gets or Sets Skeb
        /// </summary>
        [DataMember(Name = "skeb", EmitDefaultValue = true)]
        public string Skeb { get; set; }

        /// <summary>
        /// Gets or Sets Fantia
        /// </summary>
        [DataMember(Name = "fantia", EmitDefaultValue = true)]
        public string Fantia { get; set; }

        /// <summary>
        /// Gets or Sets Tumblr
        /// </summary>
        [DataMember(Name = "tumblr", EmitDefaultValue = true)]
        public string Tumblr { get; set; }

        /// <summary>
        /// Gets or Sets Youtube
        /// </summary>
        [DataMember(Name = "youtube", EmitDefaultValue = true)]
        public string Youtube { get; set; }

        /// <summary>
        /// Gets or Sets Weibo
        /// </summary>
        [DataMember(Name = "weibo", EmitDefaultValue = true)]
        public string Weibo { get; set; }

        /// <summary>
        /// Gets or Sets Naver
        /// </summary>
        [DataMember(Name = "naver", EmitDefaultValue = true)]
        public string Naver { get; set; }

        /// <summary>
        /// Gets or Sets Website
        /// </summary>
        [DataMember(Name = "website", EmitDefaultValue = true)]
        public string Website { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public int VarVersion { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updatedAt", EmitDefaultValue = false)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthorAttributes {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  ImageUrl: ").Append(ImageUrl).Append("\n");
            sb.Append("  Biography: ").Append(Biography).Append("\n");
            sb.Append("  Twitter: ").Append(Twitter).Append("\n");
            sb.Append("  Pixiv: ").Append(Pixiv).Append("\n");
            sb.Append("  MelonBook: ").Append(MelonBook).Append("\n");
            sb.Append("  FanBox: ").Append(FanBox).Append("\n");
            sb.Append("  Booth: ").Append(Booth).Append("\n");
            sb.Append("  NicoVideo: ").Append(NicoVideo).Append("\n");
            sb.Append("  Skeb: ").Append(Skeb).Append("\n");
            sb.Append("  Fantia: ").Append(Fantia).Append("\n");
            sb.Append("  Tumblr: ").Append(Tumblr).Append("\n");
            sb.Append("  Youtube: ").Append(Youtube).Append("\n");
            sb.Append("  Weibo: ").Append(Weibo).Append("\n");
            sb.Append("  Naver: ").Append(Naver).Append("\n");
            sb.Append("  Website: ").Append(Website).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthorAttributes);
        }

        /// <summary>
        /// Returns true if AuthorAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthorAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthorAttributes input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.ImageUrl == input.ImageUrl ||
                    (this.ImageUrl != null &&
                    this.ImageUrl.Equals(input.ImageUrl))
                ) && 
                (
                    this.Biography == input.Biography ||
                    this.Biography != null &&
                    input.Biography != null &&
                    this.Biography.SequenceEqual(input.Biography)
                ) && 
                (
                    this.Twitter == input.Twitter ||
                    (this.Twitter != null &&
                    this.Twitter.Equals(input.Twitter))
                ) && 
                (
                    this.Pixiv == input.Pixiv ||
                    (this.Pixiv != null &&
                    this.Pixiv.Equals(input.Pixiv))
                ) && 
                (
                    this.MelonBook == input.MelonBook ||
                    (this.MelonBook != null &&
                    this.MelonBook.Equals(input.MelonBook))
                ) && 
                (
                    this.FanBox == input.FanBox ||
                    (this.FanBox != null &&
                    this.FanBox.Equals(input.FanBox))
                ) && 
                (
                    this.Booth == input.Booth ||
                    (this.Booth != null &&
                    this.Booth.Equals(input.Booth))
                ) && 
                (
                    this.NicoVideo == input.NicoVideo ||
                    (this.NicoVideo != null &&
                    this.NicoVideo.Equals(input.NicoVideo))
                ) && 
                (
                    this.Skeb == input.Skeb ||
                    (this.Skeb != null &&
                    this.Skeb.Equals(input.Skeb))
                ) && 
                (
                    this.Fantia == input.Fantia ||
                    (this.Fantia != null &&
                    this.Fantia.Equals(input.Fantia))
                ) && 
                (
                    this.Tumblr == input.Tumblr ||
                    (this.Tumblr != null &&
                    this.Tumblr.Equals(input.Tumblr))
                ) && 
                (
                    this.Youtube == input.Youtube ||
                    (this.Youtube != null &&
                    this.Youtube.Equals(input.Youtube))
                ) && 
                (
                    this.Weibo == input.Weibo ||
                    (this.Weibo != null &&
                    this.Weibo.Equals(input.Weibo))
                ) && 
                (
                    this.Naver == input.Naver ||
                    (this.Naver != null &&
                    this.Naver.Equals(input.Naver))
                ) && 
                (
                    this.Website == input.Website ||
                    (this.Website != null &&
                    this.Website.Equals(input.Website))
                ) && 
                (
                    this.VarVersion == input.VarVersion ||
                    this.VarVersion.Equals(input.VarVersion)
                ) && 
                (
                    this.CreatedAt == input.CreatedAt ||
                    (this.CreatedAt != null &&
                    this.CreatedAt.Equals(input.CreatedAt))
                ) && 
                (
                    this.UpdatedAt == input.UpdatedAt ||
                    (this.UpdatedAt != null &&
                    this.UpdatedAt.Equals(input.UpdatedAt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.ImageUrl != null)
                {
                    hashCode = (hashCode * 59) + this.ImageUrl.GetHashCode();
                }
                if (this.Biography != null)
                {
                    hashCode = (hashCode * 59) + this.Biography.GetHashCode();
                }
                if (this.Twitter != null)
                {
                    hashCode = (hashCode * 59) + this.Twitter.GetHashCode();
                }
                if (this.Pixiv != null)
                {
                    hashCode = (hashCode * 59) + this.Pixiv.GetHashCode();
                }
                if (this.MelonBook != null)
                {
                    hashCode = (hashCode * 59) + this.MelonBook.GetHashCode();
                }
                if (this.FanBox != null)
                {
                    hashCode = (hashCode * 59) + this.FanBox.GetHashCode();
                }
                if (this.Booth != null)
                {
                    hashCode = (hashCode * 59) + this.Booth.GetHashCode();
                }
                if (this.NicoVideo != null)
                {
                    hashCode = (hashCode * 59) + this.NicoVideo.GetHashCode();
                }
                if (this.Skeb != null)
                {
                    hashCode = (hashCode * 59) + this.Skeb.GetHashCode();
                }
                if (this.Fantia != null)
                {
                    hashCode = (hashCode * 59) + this.Fantia.GetHashCode();
                }
                if (this.Tumblr != null)
                {
                    hashCode = (hashCode * 59) + this.Tumblr.GetHashCode();
                }
                if (this.Youtube != null)
                {
                    hashCode = (hashCode * 59) + this.Youtube.GetHashCode();
                }
                if (this.Weibo != null)
                {
                    hashCode = (hashCode * 59) + this.Weibo.GetHashCode();
                }
                if (this.Naver != null)
                {
                    hashCode = (hashCode * 59) + this.Naver.GetHashCode();
                }
                if (this.Website != null)
                {
                    hashCode = (hashCode * 59) + this.Website.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.VarVersion.GetHashCode();
                if (this.CreatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedAt.GetHashCode();
                }
                if (this.UpdatedAt != null)
                {
                    hashCode = (hashCode * 59) + this.UpdatedAt.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.Twitter != null) {
                // Twitter (string) pattern
Regex regexTwitter = new Regex(@"^https?://twitter\.com(/|$)", RegexOptions.CultureInvariant);
if (!regexTwitter.Match(this.Twitter).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Twitter, must match a pattern of " + regexTwitter, new [] { "Twitter" });
}
            }

            if (this.Pixiv != null) {
                // Pixiv (string) pattern
Regex regexPixiv = new Regex(@"^https?://([\w-]+\.)?pixiv\.net(/|$)", RegexOptions.CultureInvariant);
if (!regexPixiv.Match(this.Pixiv).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Pixiv, must match a pattern of " + regexPixiv, new [] { "Pixiv" });
}
            }

            if (this.MelonBook != null) {
                // MelonBook (string) pattern
Regex regexMelonBook = new Regex(@"^https?://([\w-]+\.)?melonbooks\.co\.jp(/|$)", RegexOptions.CultureInvariant);
if (!regexMelonBook.Match(this.MelonBook).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MelonBook, must match a pattern of " + regexMelonBook, new [] { "MelonBook" });
}
            }

            if (this.FanBox != null) {
                // FanBox (string) pattern
Regex regexFanBox = new Regex(@"^https?://([\w-]+\.)?fanbox\.cc(/|$)", RegexOptions.CultureInvariant);
if (!regexFanBox.Match(this.FanBox).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for FanBox, must match a pattern of " + regexFanBox, new [] { "FanBox" });
}
            }

            if (this.Booth != null) {
                // Booth (string) pattern
Regex regexBooth = new Regex(@"^https?://([\w-]+\.)?booth\.pm(/|$)", RegexOptions.CultureInvariant);
if (!regexBooth.Match(this.Booth).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Booth, must match a pattern of " + regexBooth, new [] { "Booth" });
}
            }

            if (this.NicoVideo != null) {
                // NicoVideo (string) pattern
Regex regexNicoVideo = new Regex(@"^https?://([\w-]+\.)?nicovideo\.jp(/|$)", RegexOptions.CultureInvariant);
if (!regexNicoVideo.Match(this.NicoVideo).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for NicoVideo, must match a pattern of " + regexNicoVideo, new [] { "NicoVideo" });
}
            }

            if (this.Skeb != null) {
                // Skeb (string) pattern
Regex regexSkeb = new Regex(@"^https?://([\w-]+\.)?skeb\.jp(/|$)", RegexOptions.CultureInvariant);
if (!regexSkeb.Match(this.Skeb).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Skeb, must match a pattern of " + regexSkeb, new [] { "Skeb" });
}
            }

            if (this.Fantia != null) {
                // Fantia (string) pattern
Regex regexFantia = new Regex(@"^https?://([\w-]+\.)?fantia\.jp(/|$)", RegexOptions.CultureInvariant);
if (!regexFantia.Match(this.Fantia).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Fantia, must match a pattern of " + regexFantia, new [] { "Fantia" });
}
            }

            if (this.Tumblr != null) {
                // Tumblr (string) pattern
Regex regexTumblr = new Regex(@"^https?://([\w-]+\.)?tumblr\.com(/|$)", RegexOptions.CultureInvariant);
if (!regexTumblr.Match(this.Tumblr).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Tumblr, must match a pattern of " + regexTumblr, new [] { "Tumblr" });
}
            }

            if (this.Youtube != null) {
                // Youtube (string) pattern
Regex regexYoutube = new Regex(@"^https?://www\.youtube\.com(/|$)", RegexOptions.CultureInvariant);
if (!regexYoutube.Match(this.Youtube).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Youtube, must match a pattern of " + regexYoutube, new [] { "Youtube" });
}
            }

            if (this.Weibo != null) {
                // Weibo (string) pattern
Regex regexWeibo = new Regex(@"^https?://([\w-]+\.)?weibo\.(cn|com)(/|$)", RegexOptions.CultureInvariant);
if (!regexWeibo.Match(this.Weibo).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Weibo, must match a pattern of " + regexWeibo, new [] { "Weibo" });
}
            }

            if (this.Naver != null) {
                // Naver (string) pattern
Regex regexNaver = new Regex(@"^https?://([\w-]+\.)?naver\.com(/|$)", RegexOptions.CultureInvariant);
if (!regexNaver.Match(this.Naver).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Naver, must match a pattern of " + regexNaver, new [] { "Naver" });
}
            }

            if (this.Website != null) {
                // Website (string) pattern
Regex regexWebsite = new Regex(@"^https?://", RegexOptions.CultureInvariant);
if (!regexWebsite.Match(this.Website).Success)
{
    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Website, must match a pattern of " + regexWebsite, new [] { "Website" });
}
            }

            // VarVersion (int) minimum
            if (this.VarVersion < (int)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for VarVersion, must be a value greater than or equal to 1.", new [] { "VarVersion" });
            }

            yield break;
        }
    }

}
