/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaDex.Client.OpenAPIDateConverter;

namespace MangaDex.Model
{
    /// <summary>
    /// GetStatisticsMangaUuid200ResponseStatisticsValueRating
    /// </summary>
    [DataContract(Name = "get_statistics_manga_uuid_200_response_statistics_value_rating")]
    public partial class GetStatisticsMangaUuid200ResponseStatisticsValueRating : IEquatable<GetStatisticsMangaUuid200ResponseStatisticsValueRating>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatisticsMangaUuid200ResponseStatisticsValueRating" /> class.
        /// </summary>
        /// <param name="average">Will be nullable if no ratings has been given.</param>
        /// <param name="bayesian">Average weighted on all the Manga population.</param>
        /// <param name="distribution">distribution.</param>
        public GetStatisticsMangaUuid200ResponseStatisticsValueRating(decimal? average = default(decimal?), decimal bayesian = default(decimal), GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution distribution = default(GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution))
        {
            this.Average = average;
            this.Bayesian = bayesian;
            this.Distribution = distribution;
        }

        /// <summary>
        /// Will be nullable if no ratings has been given
        /// </summary>
        /// <value>Will be nullable if no ratings has been given</value>
        [DataMember(Name = "average", EmitDefaultValue = true)]
        public decimal? Average { get; set; }

        /// <summary>
        /// Average weighted on all the Manga population
        /// </summary>
        /// <value>Average weighted on all the Manga population</value>
        [DataMember(Name = "bayesian", EmitDefaultValue = false)]
        public decimal Bayesian { get; set; }

        /// <summary>
        /// Gets or Sets Distribution
        /// </summary>
        [DataMember(Name = "distribution", EmitDefaultValue = false)]
        public GetStatisticsMangaUuid200ResponseStatisticsValueRatingDistribution Distribution { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetStatisticsMangaUuid200ResponseStatisticsValueRating {\n");
            sb.Append("  Average: ").Append(Average).Append("\n");
            sb.Append("  Bayesian: ").Append(Bayesian).Append("\n");
            sb.Append("  Distribution: ").Append(Distribution).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetStatisticsMangaUuid200ResponseStatisticsValueRating);
        }

        /// <summary>
        /// Returns true if GetStatisticsMangaUuid200ResponseStatisticsValueRating instances are equal
        /// </summary>
        /// <param name="input">Instance of GetStatisticsMangaUuid200ResponseStatisticsValueRating to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStatisticsMangaUuid200ResponseStatisticsValueRating input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Average == input.Average ||
                    (this.Average != null &&
                    this.Average.Equals(input.Average))
                ) && 
                (
                    this.Bayesian == input.Bayesian ||
                    this.Bayesian.Equals(input.Bayesian)
                ) && 
                (
                    this.Distribution == input.Distribution ||
                    (this.Distribution != null &&
                    this.Distribution.Equals(input.Distribution))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Average != null)
                {
                    hashCode = (hashCode * 59) + this.Average.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Bayesian.GetHashCode();
                if (this.Distribution != null)
                {
                    hashCode = (hashCode * 59) + this.Distribution.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
