/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MangaDex.Client.OpenAPIDateConverter;

namespace MangaDex.Model
{
    /// <summary>
    /// Comments-related statistics of an entity. If it is &#x60;null&#x60;, the entity doesn&#39;t have a backing comments thread, and therefore has no comments yet. 
    /// </summary>
    [DataContract(Name = "StatisticsDetailsComments")]
    public partial class StatisticsDetailsComments : IEquatable<StatisticsDetailsComments>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsDetailsComments" /> class.
        /// </summary>
        /// <param name="threadId">The id of the thread backing the comments for that entity on the MangaDex Forums..</param>
        /// <param name="repliesCount">The number of replies on the MangaDex Forums thread backing this entity&#39;s comments. This excludes the initial comment that opens the thread, which is created by our systems. .</param>
        public StatisticsDetailsComments(decimal threadId = default(decimal), decimal repliesCount = default(decimal))
        {
            this.ThreadId = threadId;
            this.RepliesCount = repliesCount;
        }

        /// <summary>
        /// The id of the thread backing the comments for that entity on the MangaDex Forums.
        /// </summary>
        /// <value>The id of the thread backing the comments for that entity on the MangaDex Forums.</value>
        [DataMember(Name = "threadId", EmitDefaultValue = false)]
        [JsonPropertyName("threadId")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public decimal ThreadId { get; set; }

        /// <summary>
        /// The number of replies on the MangaDex Forums thread backing this entity&#39;s comments. This excludes the initial comment that opens the thread, which is created by our systems. 
        /// </summary>
        /// <value>The number of replies on the MangaDex Forums thread backing this entity&#39;s comments. This excludes the initial comment that opens the thread, which is created by our systems. </value>
        [DataMember(Name = "repliesCount", EmitDefaultValue = false)]
        [JsonPropertyName("repliesCount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public decimal RepliesCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatisticsDetailsComments {\n");
            sb.Append("  ThreadId: ").Append(ThreadId).Append("\n");
            sb.Append("  RepliesCount: ").Append(RepliesCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return System.Text.Json.JsonSerializer.Serialize(this, MangaDex.Client.SerializerOptions.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatisticsDetailsComments);
        }

        /// <summary>
        /// Returns true if StatisticsDetailsComments instances are equal
        /// </summary>
        /// <param name="input">Instance of StatisticsDetailsComments to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatisticsDetailsComments input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ThreadId == input.ThreadId ||
                    this.ThreadId.Equals(input.ThreadId)
                ) && 
                (
                    this.RepliesCount == input.RepliesCount ||
                    this.RepliesCount.Equals(input.RepliesCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.ThreadId.GetHashCode();
                hashCode = (hashCode * 59) + this.RepliesCount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // ThreadId (decimal) minimum
            if (this.ThreadId < (decimal)1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for ThreadId, must be a value greater than or equal to 1.", new [] { "ThreadId" });
            }

            // RepliesCount (decimal) minimum
            if (this.RepliesCount < (decimal)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RepliesCount, must be a value greater than or equal to 0.", new [] { "RepliesCount" });
            }

            yield break;
        }
    }

}
