/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MangaDex.Client;
using MangaDex.Model;

namespace MangaDex.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Activate account
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        AccountActivateResponse GetAccountActivateCode(string code, int operationIndex = 0);

        /// <summary>
        /// Activate account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        ApiResponse<AccountActivateResponse> GetAccountActivateCodeWithHttpInfo(string code, int operationIndex = 0);
        /// <summary>
        /// Account username available
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountAvailable200Response</returns>
        [Obsolete]
        GetAccountAvailable200Response GetAccountAvailable(string username, int operationIndex = 0);

        /// <summary>
        /// Account username available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountAvailable200Response</returns>
        [Obsolete]
        ApiResponse<GetAccountAvailable200Response> GetAccountAvailableWithHttpInfo(string username, int operationIndex = 0);
        /// <summary>
        /// Resend Activation code
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        AccountActivateResponse PostAccountActivateResend(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0);

        /// <summary>
        /// Resend Activation code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        ApiResponse<AccountActivateResponse> PostAccountActivateResendWithHttpInfo(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0);
        /// <summary>
        /// Create Account
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserResponse</returns>
        [Obsolete]
        UserResponse PostAccountCreate(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0);

        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserResponse</returns>
        [Obsolete]
        ApiResponse<UserResponse> PostAccountCreateWithHttpInfo(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0);
        /// <summary>
        /// Recover given Account
        /// </summary>
        /// <remarks>
        /// You can only request Account Recovery once per Hour for the same Email Address
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        AccountActivateResponse PostAccountRecover(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0);

        /// <summary>
        /// Recover given Account
        /// </summary>
        /// <remarks>
        /// You can only request Account Recovery once per Hour for the same Email Address
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        ApiResponse<AccountActivateResponse> PostAccountRecoverWithHttpInfo(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0);
        /// <summary>
        /// Complete Account recover
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        AccountActivateResponse PostAccountRecoverCode(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0);

        /// <summary>
        /// Complete Account recover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        ApiResponse<AccountActivateResponse> PostAccountRecoverCodeWithHttpInfo(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Activate account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<AccountActivateResponse> GetAccountActivateCodeAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Activate account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<AccountActivateResponse>> GetAccountActivateCodeWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Account username available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountAvailable200Response</returns>
        [Obsolete]
        System.Threading.Tasks.Task<GetAccountAvailable200Response> GetAccountAvailableAsync(string username, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Account username available
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountAvailable200Response)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<GetAccountAvailable200Response>> GetAccountAvailableWithHttpInfoAsync(string username, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Resend Activation code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<AccountActivateResponse> PostAccountActivateResendAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Resend Activation code
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<AccountActivateResponse>> PostAccountActivateResendWithHttpInfoAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<UserResponse> PostAccountCreateAsync(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Account
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<UserResponse>> PostAccountCreateWithHttpInfoAsync(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Recover given Account
        /// </summary>
        /// <remarks>
        /// You can only request Account Recovery once per Hour for the same Email Address
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<AccountActivateResponse> PostAccountRecoverAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Recover given Account
        /// </summary>
        /// <remarks>
        /// You can only request Account Recovery once per Hour for the same Email Address
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<AccountActivateResponse>> PostAccountRecoverWithHttpInfoAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Complete Account recover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        System.Threading.Tasks.Task<AccountActivateResponse> PostAccountRecoverCodeAsync(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Complete Account recover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        System.Threading.Tasks.Task<ApiResponse<AccountActivateResponse>> PostAccountRecoverCodeWithHttpInfoAsync(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAccountApi : IAccountApiSync, IAccountApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AccountApi : IAccountApi
    {
        private MangaDex.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AccountApi(string basePath)
        {
            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                new MangaDex.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AccountApi(MangaDex.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AccountApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AccountApi(MangaDex.Client.ISynchronousClient client, MangaDex.Client.IAsynchronousClient asyncClient, MangaDex.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MangaDex.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MangaDex.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MangaDex.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MangaDex.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Activate account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        public AccountActivateResponse GetAccountActivateCode(string code, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = GetAccountActivateCodeWithHttpInfo(code);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Activate account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<AccountActivateResponse> GetAccountActivateCodeWithHttpInfo(string code, int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'code' when calling AccountApi->GetAccountActivateCode");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", MangaDex.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "AccountApi.GetAccountActivateCode";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AccountActivateResponse>("/account/activate/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountActivateCode", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Activate account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AccountActivateResponse> GetAccountActivateCodeAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = await GetAccountActivateCodeWithHttpInfoAsync(code, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Activate account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<AccountActivateResponse>> GetAccountActivateCodeWithHttpInfoAsync(string code, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'code' when calling AccountApi->GetAccountActivateCode");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", MangaDex.Client.ClientUtils.ParameterToString(code)); // path parameter

            localVarRequestOptions.Operation = "AccountApi.GetAccountActivateCode";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AccountActivateResponse>("/account/activate/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountActivateCode", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Account username available 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAccountAvailable200Response</returns>
        [Obsolete]
        public GetAccountAvailable200Response GetAccountAvailable(string username, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetAccountAvailable200Response> localVarResponse = GetAccountAvailableWithHttpInfo(username);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Account username available 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAccountAvailable200Response</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<GetAccountAvailable200Response> GetAccountAvailableWithHttpInfo(string username, int operationIndex = 0)
        {
            // verify the required parameter 'username' is set
            if (username == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'username' when calling AccountApi->GetAccountAvailable");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "username", username));

            localVarRequestOptions.Operation = "AccountApi.GetAccountAvailable";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAccountAvailable200Response>("/account/available", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountAvailable", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Account username available 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAccountAvailable200Response</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<GetAccountAvailable200Response> GetAccountAvailableAsync(string username, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetAccountAvailable200Response> localVarResponse = await GetAccountAvailableWithHttpInfoAsync(username, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Account username available 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="username">Username to check for avaibility</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAccountAvailable200Response)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetAccountAvailable200Response>> GetAccountAvailableWithHttpInfoAsync(string username, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'username' is set
            if (username == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'username' when calling AccountApi->GetAccountAvailable");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "username", username));

            localVarRequestOptions.Operation = "AccountApi.GetAccountAvailable";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAccountAvailable200Response>("/account/available", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAccountAvailable", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Resend Activation code 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        public AccountActivateResponse PostAccountActivateResend(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = PostAccountActivateResendWithHttpInfo(contentType, sendAccountActivationCode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Resend Activation code 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<AccountActivateResponse> PostAccountActivateResendWithHttpInfo(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountActivateResend");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = sendAccountActivationCode;

            localVarRequestOptions.Operation = "AccountApi.PostAccountActivateResend";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AccountActivateResponse>("/account/activate/resend", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountActivateResend", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Resend Activation code 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AccountActivateResponse> PostAccountActivateResendAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = await PostAccountActivateResendWithHttpInfoAsync(contentType, sendAccountActivationCode, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Resend Activation code 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<AccountActivateResponse>> PostAccountActivateResendWithHttpInfoAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountActivateResend");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = sendAccountActivationCode;

            localVarRequestOptions.Operation = "AccountApi.PostAccountActivateResend";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AccountActivateResponse>("/account/activate/resend", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountActivateResend", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UserResponse</returns>
        [Obsolete]
        public UserResponse PostAccountCreate(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<UserResponse> localVarResponse = PostAccountCreateWithHttpInfo(contentType, createAccount);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UserResponse</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<UserResponse> PostAccountCreateWithHttpInfo(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountCreate");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = createAccount;

            localVarRequestOptions.Operation = "AccountApi.PostAccountCreate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserResponse>("/account/create", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<UserResponse> PostAccountCreateAsync(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<UserResponse> localVarResponse = await PostAccountCreateWithHttpInfoAsync(contentType, createAccount, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Account 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="createAccount">The size of the body is limited to 4KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserResponse)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<UserResponse>> PostAccountCreateWithHttpInfoAsync(string contentType, CreateAccount createAccount = default(CreateAccount), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountCreate");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = createAccount;

            localVarRequestOptions.Operation = "AccountApi.PostAccountCreate";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UserResponse>("/account/create", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountCreate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recover given Account You can only request Account Recovery once per Hour for the same Email Address
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        public AccountActivateResponse PostAccountRecover(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = PostAccountRecoverWithHttpInfo(contentType, sendAccountActivationCode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Recover given Account You can only request Account Recovery once per Hour for the same Email Address
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<AccountActivateResponse> PostAccountRecoverWithHttpInfo(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountRecover");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = sendAccountActivationCode;

            localVarRequestOptions.Operation = "AccountApi.PostAccountRecover";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AccountActivateResponse>("/account/recover", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountRecover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Recover given Account You can only request Account Recovery once per Hour for the same Email Address
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AccountActivateResponse> PostAccountRecoverAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = await PostAccountRecoverWithHttpInfoAsync(contentType, sendAccountActivationCode, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Recover given Account You can only request Account Recovery once per Hour for the same Email Address
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="contentType"></param>
        /// <param name="sendAccountActivationCode">The size of the body is limited to 1KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<AccountActivateResponse>> PostAccountRecoverWithHttpInfoAsync(string contentType, SendAccountActivationCode sendAccountActivationCode = default(SendAccountActivationCode), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountRecover");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = sendAccountActivationCode;

            localVarRequestOptions.Operation = "AccountApi.PostAccountRecover";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AccountActivateResponse>("/account/recover", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountRecover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Complete Account recover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AccountActivateResponse</returns>
        [Obsolete]
        public AccountActivateResponse PostAccountRecoverCode(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = PostAccountRecoverCodeWithHttpInfo(code, contentType, recoverCompleteBody);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete Account recover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AccountActivateResponse</returns>
        [Obsolete]
        public MangaDex.Client.ApiResponse<AccountActivateResponse> PostAccountRecoverCodeWithHttpInfo(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0)
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'code' when calling AccountApi->PostAccountRecoverCode");
            }

            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountRecoverCode");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", MangaDex.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = recoverCompleteBody;

            localVarRequestOptions.Operation = "AccountApi.PostAccountRecoverCode";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<AccountActivateResponse>("/account/recover/{code}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountRecoverCode", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Complete Account recover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AccountActivateResponse</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<AccountActivateResponse> PostAccountRecoverCodeAsync(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<AccountActivateResponse> localVarResponse = await PostAccountRecoverCodeWithHttpInfoAsync(code, contentType, recoverCompleteBody, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Complete Account recover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="code"></param>
        /// <param name="contentType"></param>
        /// <param name="recoverCompleteBody">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AccountActivateResponse)</returns>
        [Obsolete]
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<AccountActivateResponse>> PostAccountRecoverCodeWithHttpInfoAsync(string code, string contentType, RecoverCompleteBody recoverCompleteBody = default(RecoverCompleteBody), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'code' is set
            if (code == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'code' when calling AccountApi->PostAccountRecoverCode");
            }

            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling AccountApi->PostAccountRecoverCode");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("code", MangaDex.Client.ClientUtils.ParameterToString(code)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = recoverCompleteBody;

            localVarRequestOptions.Operation = "AccountApi.PostAccountRecoverCode";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<AccountActivateResponse>("/account/recover/{code}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PostAccountRecoverCode", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
