/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MangaDex.Client;
using MangaDex.Model;

namespace MangaDex.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAtHomeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get MangaDex@Home server URL
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAtHomeServerChapterId200Response</returns>
        GetAtHomeServerChapterId200Response GetAtHomeServerChapterId(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0);

        /// <summary>
        /// Get MangaDex@Home server URL
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAtHomeServerChapterId200Response</returns>
        ApiResponse<GetAtHomeServerChapterId200Response> GetAtHomeServerChapterIdWithHttpInfo(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAtHomeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get MangaDex@Home server URL
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAtHomeServerChapterId200Response</returns>
        System.Threading.Tasks.Task<GetAtHomeServerChapterId200Response> GetAtHomeServerChapterIdAsync(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get MangaDex@Home server URL
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAtHomeServerChapterId200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetAtHomeServerChapterId200Response>> GetAtHomeServerChapterIdWithHttpInfoAsync(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAtHomeApi : IAtHomeApiSync, IAtHomeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AtHomeApi : IAtHomeApi
    {
        private MangaDex.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AtHomeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AtHomeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AtHomeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AtHomeApi(string basePath)
        {
            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                new MangaDex.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AtHomeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AtHomeApi(MangaDex.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AtHomeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AtHomeApi(MangaDex.Client.ISynchronousClient client, MangaDex.Client.IAsynchronousClient asyncClient, MangaDex.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MangaDex.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MangaDex.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MangaDex.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MangaDex.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get MangaDex@Home server URL 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetAtHomeServerChapterId200Response</returns>
        public GetAtHomeServerChapterId200Response GetAtHomeServerChapterId(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetAtHomeServerChapterId200Response> localVarResponse = GetAtHomeServerChapterIdWithHttpInfo(chapterId, forcePort443);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get MangaDex@Home server URL 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetAtHomeServerChapterId200Response</returns>
        public MangaDex.Client.ApiResponse<GetAtHomeServerChapterId200Response> GetAtHomeServerChapterIdWithHttpInfo(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("chapterId", MangaDex.Client.ClientUtils.ParameterToString(chapterId)); // path parameter
            if (forcePort443 != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "forcePort443", forcePort443));
            }

            localVarRequestOptions.Operation = "AtHomeApi.GetAtHomeServerChapterId";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<GetAtHomeServerChapterId200Response>("/at-home/server/{chapterId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAtHomeServerChapterId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get MangaDex@Home server URL 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetAtHomeServerChapterId200Response</returns>
        public async System.Threading.Tasks.Task<GetAtHomeServerChapterId200Response> GetAtHomeServerChapterIdAsync(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetAtHomeServerChapterId200Response> localVarResponse = await GetAtHomeServerChapterIdWithHttpInfoAsync(chapterId, forcePort443, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get MangaDex@Home server URL 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapterId">Chapter ID</param>
        /// <param name="forcePort443">Force selecting from MangaDex@Home servers that use the standard HTTPS port 443.  While the conventional port for HTTPS traffic is 443 and servers are encouraged to use it, it is not a hard requirement as it technically isn&#39;t anything special.  However, some misbehaving school/office network will at time block traffic to non-standard ports, and setting this flag to &#x60;true&#x60; will ensure selection of a server that uses these. (optional, default to false)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetAtHomeServerChapterId200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetAtHomeServerChapterId200Response>> GetAtHomeServerChapterIdWithHttpInfoAsync(Guid chapterId, bool? forcePort443 = default(bool?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("chapterId", MangaDex.Client.ClientUtils.ParameterToString(chapterId)); // path parameter
            if (forcePort443 != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "forcePort443", forcePort443));
            }

            localVarRequestOptions.Operation = "AtHomeApi.GetAtHomeServerChapterId";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetAtHomeServerChapterId200Response>("/at-home/server/{chapterId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAtHomeServerChapterId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
