/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MangaDex.Client;
using MangaDex.Model;

namespace MangaDex.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICoverApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Delete Cover
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Response</returns>
        Response DeleteCover(Guid mangaOrCoverId, int operationIndex = 0);

        /// <summary>
        /// Delete Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Response</returns>
        ApiResponse<Response> DeleteCoverWithHttpInfo(Guid mangaOrCoverId, int operationIndex = 0);
        /// <summary>
        /// Edit Cover
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        CoverResponse EditCover(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0);

        /// <summary>
        /// Edit Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        ApiResponse<CoverResponse> EditCoverWithHttpInfo(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0);
        /// <summary>
        /// CoverArt list
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverList</returns>
        CoverList GetCover(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// CoverArt list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverList</returns>
        ApiResponse<CoverList> GetCoverWithHttpInfo(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// Get Cover
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        CoverResponse GetCoverId(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0);

        /// <summary>
        /// Get Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        ApiResponse<CoverResponse> GetCoverIdWithHttpInfo(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0);
        /// <summary>
        /// Upload Cover
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        CoverResponse UploadCover(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0);

        /// <summary>
        /// Upload Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        ApiResponse<CoverResponse> UploadCoverWithHttpInfo(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICoverApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Delete Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Response</returns>
        System.Threading.Tasks.Task<Response> DeleteCoverAsync(Guid mangaOrCoverId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<Response>> DeleteCoverWithHttpInfoAsync(Guid mangaOrCoverId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Edit Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        System.Threading.Tasks.Task<CoverResponse> EditCoverAsync(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Edit Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CoverResponse>> EditCoverWithHttpInfoAsync(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// CoverArt list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverList</returns>
        System.Threading.Tasks.Task<CoverList> GetCoverAsync(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// CoverArt list
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverList)</returns>
        System.Threading.Tasks.Task<ApiResponse<CoverList>> GetCoverWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        System.Threading.Tasks.Task<CoverResponse> GetCoverIdAsync(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CoverResponse>> GetCoverIdWithHttpInfoAsync(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Upload Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        System.Threading.Tasks.Task<CoverResponse> UploadCoverAsync(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Upload Cover
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CoverResponse>> UploadCoverWithHttpInfoAsync(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ICoverApi : ICoverApiSync, ICoverApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class CoverApi : ICoverApi
    {
        private MangaDex.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="CoverApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CoverApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CoverApi"/> class.
        /// </summary>
        /// <returns></returns>
        public CoverApi(string basePath)
        {
            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                new MangaDex.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CoverApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public CoverApi(MangaDex.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CoverApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public CoverApi(MangaDex.Client.ISynchronousClient client, MangaDex.Client.IAsynchronousClient asyncClient, MangaDex.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MangaDex.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MangaDex.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MangaDex.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MangaDex.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Delete Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Response</returns>
        public Response DeleteCover(Guid mangaOrCoverId, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<Response> localVarResponse = DeleteCoverWithHttpInfo(mangaOrCoverId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Response</returns>
        public MangaDex.Client.ApiResponse<Response> DeleteCoverWithHttpInfo(Guid mangaOrCoverId, int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter

            localVarRequestOptions.Operation = "CoverApi.DeleteCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<Response>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Response</returns>
        public async System.Threading.Tasks.Task<Response> DeleteCoverAsync(Guid mangaOrCoverId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<Response> localVarResponse = await DeleteCoverWithHttpInfoAsync(mangaOrCoverId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<Response>> DeleteCoverWithHttpInfoAsync(Guid mangaOrCoverId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter

            localVarRequestOptions.Operation = "CoverApi.DeleteCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Response>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Edit Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        public CoverResponse EditCover(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = EditCoverWithHttpInfo(mangaOrCoverId, contentType, coverEdit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Edit Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        public MangaDex.Client.ApiResponse<CoverResponse> EditCoverWithHttpInfo(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling CoverApi->EditCover");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = coverEdit;

            localVarRequestOptions.Operation = "CoverApi.EditCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EditCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Edit Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        public async System.Threading.Tasks.Task<CoverResponse> EditCoverAsync(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = await EditCoverWithHttpInfoAsync(mangaOrCoverId, contentType, coverEdit, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Edit Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="coverEdit">The size of the body is limited to 2KB. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<CoverResponse>> EditCoverWithHttpInfoAsync(Guid mangaOrCoverId, string contentType, CoverEdit coverEdit = default(CoverEdit), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling CoverApi->EditCover");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            localVarRequestOptions.Data = coverEdit;

            localVarRequestOptions.Operation = "CoverApi.EditCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("EditCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// CoverArt list 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverList</returns>
        public CoverList GetCover(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<CoverList> localVarResponse = GetCoverWithHttpInfo(limit, offset, manga, ids, uploaders, locales, order, includes);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CoverArt list 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverList</returns>
        public MangaDex.Client.ApiResponse<CoverList> GetCoverWithHttpInfo(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (manga != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "manga[]", manga));
            }
            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "ids[]", ids));
            }
            if (uploaders != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "uploaders[]", uploaders));
            }
            if (locales != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "locales[]", locales));
            }
            if (order != null)
            {
                if (order.CreatedAt != null)
                {
                    localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "order[createdAt]", order.CreatedAt));
                }
                if (order.UpdatedAt != null)
                {
                    localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "order[updatedAt]", order.UpdatedAt));
                }
                if (order.Volume != null)
                {
                    localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "order[volume]", order.Volume));
                }
            }
            if (includes != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "includes[]", includes));
            }

            localVarRequestOptions.Operation = "CoverApi.GetCover";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<CoverList>("/cover", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// CoverArt list 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverList</returns>
        public async System.Threading.Tasks.Task<CoverList> GetCoverAsync(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<CoverList> localVarResponse = await GetCoverWithHttpInfoAsync(limit, offset, manga, ids, uploaders, locales, order, includes, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// CoverArt list 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 10)</param>
        /// <param name="offset"> (optional)</param>
        /// <param name="manga">Manga ids (limited to 100 per request) (optional)</param>
        /// <param name="ids">Covers ids (limited to 100 per request) (optional)</param>
        /// <param name="uploaders">User ids (limited to 100 per request) (optional)</param>
        /// <param name="locales">Locales of cover art (limited to 100 per request) (optional)</param>
        /// <param name="order"> (optional)</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverList)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<CoverList>> GetCoverWithHttpInfoAsync(int? limit = default(int?), int? offset = default(int?), List<Guid> manga = default(List<Guid>), List<Guid> ids = default(List<Guid>), List<Guid> uploaders = default(List<Guid>), List<string> locales = default(List<string>), GetCoverOrderParameter order = default(GetCoverOrderParameter), List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (manga != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "manga[]", manga));
            }
            if (ids != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "ids[]", ids));
            }
            if (uploaders != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "uploaders[]", uploaders));
            }
            if (locales != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "locales[]", locales));
            }
            if (order != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("", "order", order));
            }
            if (includes != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "includes[]", includes));
            }

            localVarRequestOptions.Operation = "CoverApi.GetCover";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CoverList>("/cover", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        public CoverResponse GetCoverId(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = GetCoverIdWithHttpInfo(mangaOrCoverId, includes);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        public MangaDex.Client.ApiResponse<CoverResponse> GetCoverIdWithHttpInfo(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            if (includes != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "includes[]", includes));
            }

            localVarRequestOptions.Operation = "CoverApi.GetCoverId";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCoverId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        public async System.Threading.Tasks.Task<CoverResponse> GetCoverIdAsync(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = await GetCoverIdWithHttpInfoAsync(mangaOrCoverId, includes, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="includes"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<CoverResponse>> GetCoverIdWithHttpInfoAsync(Guid mangaOrCoverId, List<string> includes = default(List<string>), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            if (includes != null)
            {
                localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("multi", "includes[]", includes));
            }

            localVarRequestOptions.Operation = "CoverApi.GetCoverId";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetCoverId", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upload Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>CoverResponse</returns>
        public CoverResponse UploadCover(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = UploadCoverWithHttpInfo(mangaOrCoverId, contentType, file, volume, description, locale);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Upload Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of CoverResponse</returns>
        public MangaDex.Client.ApiResponse<CoverResponse> UploadCoverWithHttpInfo(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0)
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling CoverApi->UploadCover");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }
            if (volume != null)
            {
                localVarRequestOptions.FormParameters.Add("volume", MangaDex.Client.ClientUtils.ParameterToString(volume)); // form parameter
            }
            if (description != null)
            {
                localVarRequestOptions.FormParameters.Add("description", MangaDex.Client.ClientUtils.ParameterToString(description)); // form parameter
            }
            if (locale != null)
            {
                localVarRequestOptions.FormParameters.Add("locale", MangaDex.Client.ClientUtils.ParameterToString(locale)); // form parameter
            }

            localVarRequestOptions.Operation = "CoverApi.UploadCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Upload Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CoverResponse</returns>
        public async System.Threading.Tasks.Task<CoverResponse> UploadCoverAsync(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<CoverResponse> localVarResponse = await UploadCoverWithHttpInfoAsync(mangaOrCoverId, contentType, file, volume, description, locale, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Upload Cover 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="mangaOrCoverId">Is Manga UUID on POST</param>
        /// <param name="contentType"></param>
        /// <param name="file"> (optional)</param>
        /// <param name="volume"> (optional)</param>
        /// <param name="description"> (optional)</param>
        /// <param name="locale"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CoverResponse)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<CoverResponse>> UploadCoverWithHttpInfoAsync(Guid mangaOrCoverId, string contentType, System.IO.Stream file = default(System.IO.Stream), string volume = default(string), string description = default(string), string locale = default(string), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'contentType' is set
            if (contentType == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'contentType' when calling CoverApi->UploadCover");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("mangaOrCoverId", MangaDex.Client.ClientUtils.ParameterToString(mangaOrCoverId)); // path parameter
            localVarRequestOptions.HeaderParameters.Add("Content-Type", MangaDex.Client.ClientUtils.ParameterToString(contentType)); // header parameter
            if (file != null)
            {
                localVarRequestOptions.FileParameters.Add("file", file);
            }
            if (volume != null)
            {
                localVarRequestOptions.FormParameters.Add("volume", MangaDex.Client.ClientUtils.ParameterToString(volume)); // form parameter
            }
            if (description != null)
            {
                localVarRequestOptions.FormParameters.Add("description", MangaDex.Client.ClientUtils.ParameterToString(description)); // form parameter
            }
            if (locale != null)
            {
                localVarRequestOptions.FormParameters.Add("locale", MangaDex.Client.ClientUtils.ParameterToString(locale)); // form parameter
            }

            localVarRequestOptions.Operation = "CoverApi.UploadCover";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<CoverResponse>("/cover/{mangaOrCoverId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UploadCover", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
