/*
 * MangaDex API
 *
 * MangaDex is an ad-free manga reader offering high-quality images!  This document details our API as it is right now. It is in no way a promise to never change it, although we will endeavour to publicly notify any major change.  # Acceptable use policy  Usage of our services implies acceptance of the following: - You **MUST** credit us - You **MUST** credit scanlation groups if you offer the ability to read chapters - You **CANNOT** run ads or paid services on your website and/or apps  These may change at any time for any and no reason and it is up to you check for updates from time to time.  # Security issues  If you believe you found a security issue in our API, please check our [security.txt](/security.txt) to get in touch privately. 
 *
 * The version of the OpenAPI document: 5.10.0
 * Contact: support@mangadex.org
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MangaDex.Client;
using MangaDex.Model;

namespace MangaDex.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get statistics about given chapter
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        GetStatisticsChapterUuid200Response GetStatisticsChapterUuid(Guid uuid, int operationIndex = 0);

        /// <summary>
        /// Get statistics about given chapter
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsChapterUuidWithHttpInfo(Guid uuid, int operationIndex = 0);
        /// <summary>
        /// Get statistics about given chapters
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        GetStatisticsChapterUuid200Response GetStatisticsChapters(List<Guid> chapter, int operationIndex = 0);

        /// <summary>
        /// Get statistics about given chapters
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsChaptersWithHttpInfo(List<Guid> chapter, int operationIndex = 0);
        /// <summary>
        /// Get statistics about given scanlation group
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        GetStatisticsChapterUuid200Response GetStatisticsGroupUuid(Guid uuid, int operationIndex = 0);

        /// <summary>
        /// Get statistics about given scanlation group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsGroupUuidWithHttpInfo(Guid uuid, int operationIndex = 0);
        /// <summary>
        /// Get statistics about given groups
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        GetStatisticsChapterUuid200Response GetStatisticsGroups(List<Guid> group, int operationIndex = 0);

        /// <summary>
        /// Get statistics about given groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsGroupsWithHttpInfo(List<Guid> group, int operationIndex = 0);
        /// <summary>
        /// Find statistics about given Manga
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsManga200Response</returns>
        GetStatisticsManga200Response GetStatisticsManga(List<Guid> manga, int operationIndex = 0);

        /// <summary>
        /// Find statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsManga200Response</returns>
        ApiResponse<GetStatisticsManga200Response> GetStatisticsMangaWithHttpInfo(List<Guid> manga, int operationIndex = 0);
        /// <summary>
        /// Get statistics about given Manga
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsMangaUuid200Response</returns>
        GetStatisticsMangaUuid200Response GetStatisticsMangaUuid(Guid uuid, int operationIndex = 0);

        /// <summary>
        /// Get statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsMangaUuid200Response</returns>
        ApiResponse<GetStatisticsMangaUuid200Response> GetStatisticsMangaUuidWithHttpInfo(Guid uuid, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get statistics about given chapter
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsChapterUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get statistics about given chapter
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsChapterUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get statistics about given chapters
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsChaptersAsync(List<Guid> chapter, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get statistics about given chapters
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsChaptersWithHttpInfoAsync(List<Guid> chapter, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get statistics about given scanlation group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsGroupUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get statistics about given scanlation group
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsGroupUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get statistics about given groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsGroupsAsync(List<Guid> group, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get statistics about given groups
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsGroupsWithHttpInfoAsync(List<Guid> group, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Find statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsManga200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsManga200Response> GetStatisticsMangaAsync(List<Guid> manga, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Find statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsManga200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsManga200Response>> GetStatisticsMangaWithHttpInfoAsync(List<Guid> manga, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsMangaUuid200Response</returns>
        System.Threading.Tasks.Task<GetStatisticsMangaUuid200Response> GetStatisticsMangaUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get statistics about given Manga
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsMangaUuid200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetStatisticsMangaUuid200Response>> GetStatisticsMangaUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IStatisticsApi : IStatisticsApiSync, IStatisticsApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class StatisticsApi : IStatisticsApi
    {
        private MangaDex.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatisticsApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public StatisticsApi(string basePath)
        {
            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                new MangaDex.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public StatisticsApi(MangaDex.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MangaDex.Client.Configuration.MergeConfigurations(
                MangaDex.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MangaDex.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public StatisticsApi(MangaDex.Client.ISynchronousClient client, MangaDex.Client.IAsynchronousClient asyncClient, MangaDex.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MangaDex.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MangaDex.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MangaDex.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MangaDex.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MangaDex.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get statistics about given chapter 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        public GetStatisticsChapterUuid200Response GetStatisticsChapterUuid(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = GetStatisticsChapterUuidWithHttpInfo(uuid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given chapter 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsChapterUuidWithHttpInfo(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsChapterUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsChapterUuid200Response>("/statistics/chapter/{uuid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsChapterUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given chapter 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsChapterUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = await GetStatisticsChapterUuidWithHttpInfoAsync(uuid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given chapter 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsChapterUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsChapterUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsChapterUuid200Response>("/statistics/chapter/{uuid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsChapterUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given chapters 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        public GetStatisticsChapterUuid200Response GetStatisticsChapters(List<Guid> chapter, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = GetStatisticsChaptersWithHttpInfo(chapter);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given chapters 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsChaptersWithHttpInfo(List<Guid> chapter, int operationIndex = 0)
        {
            // verify the required parameter 'chapter' is set
            if (chapter == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'chapter' when calling StatisticsApi->GetStatisticsChapters");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsChapters";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsChapterUuid200Response>("/statistics/chapter", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsChapters", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given chapters 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsChaptersAsync(List<Guid> chapter, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = await GetStatisticsChaptersWithHttpInfoAsync(chapter, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given chapters 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="chapter"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsChaptersWithHttpInfoAsync(List<Guid> chapter, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'chapter' is set
            if (chapter == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'chapter' when calling StatisticsApi->GetStatisticsChapters");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("csv", "chapter[]", chapter));

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsChapters";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsChapterUuid200Response>("/statistics/chapter", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsChapters", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given scanlation group 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        public GetStatisticsChapterUuid200Response GetStatisticsGroupUuid(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = GetStatisticsGroupUuidWithHttpInfo(uuid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given scanlation group 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsGroupUuidWithHttpInfo(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsGroupUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsChapterUuid200Response>("/statistics/group/{uuid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsGroupUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given scanlation group 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsGroupUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = await GetStatisticsGroupUuidWithHttpInfoAsync(uuid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given scanlation group 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsGroupUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsGroupUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsChapterUuid200Response>("/statistics/group/{uuid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsGroupUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given groups 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsChapterUuid200Response</returns>
        public GetStatisticsChapterUuid200Response GetStatisticsGroups(List<Guid> group, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = GetStatisticsGroupsWithHttpInfo(group);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given groups 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsChapterUuid200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> GetStatisticsGroupsWithHttpInfo(List<Guid> group, int operationIndex = 0)
        {
            // verify the required parameter 'group' is set
            if (group == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'group' when calling StatisticsApi->GetStatisticsGroups");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsGroups";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsChapterUuid200Response>("/statistics/group", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsGroups", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given groups 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsChapterUuid200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsChapterUuid200Response> GetStatisticsGroupsAsync(List<Guid> group, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response> localVarResponse = await GetStatisticsGroupsWithHttpInfoAsync(group, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given groups 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="group"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsChapterUuid200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsChapterUuid200Response>> GetStatisticsGroupsWithHttpInfoAsync(List<Guid> group, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'group' is set
            if (group == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'group' when calling StatisticsApi->GetStatisticsGroups");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("csv", "group[]", group));

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsGroups";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsChapterUuid200Response>("/statistics/group", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsGroups", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsManga200Response</returns>
        public GetStatisticsManga200Response GetStatisticsManga(List<Guid> manga, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsManga200Response> localVarResponse = GetStatisticsMangaWithHttpInfo(manga);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsManga200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsManga200Response> GetStatisticsMangaWithHttpInfo(List<Guid> manga, int operationIndex = 0)
        {
            // verify the required parameter 'manga' is set
            if (manga == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'manga' when calling StatisticsApi->GetStatisticsManga");
            }

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsManga";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsManga200Response>("/statistics/manga", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsManga", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Find statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsManga200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsManga200Response> GetStatisticsMangaAsync(List<Guid> manga, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsManga200Response> localVarResponse = await GetStatisticsMangaWithHttpInfoAsync(manga, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Find statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="manga"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsManga200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsManga200Response>> GetStatisticsMangaWithHttpInfoAsync(List<Guid> manga, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'manga' is set
            if (manga == null)
            {
                throw new MangaDex.Client.ApiException(400, "Missing required parameter 'manga' when calling StatisticsApi->GetStatisticsManga");
            }


            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MangaDex.Client.ClientUtils.ParameterToMultiMap("csv", "manga[]", manga));

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsManga";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsManga200Response>("/statistics/manga", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsManga", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetStatisticsMangaUuid200Response</returns>
        public GetStatisticsMangaUuid200Response GetStatisticsMangaUuid(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.ApiResponse<GetStatisticsMangaUuid200Response> localVarResponse = GetStatisticsMangaUuidWithHttpInfo(uuid);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetStatisticsMangaUuid200Response</returns>
        public MangaDex.Client.ApiResponse<GetStatisticsMangaUuid200Response> GetStatisticsMangaUuidWithHttpInfo(Guid uuid, int operationIndex = 0)
        {
            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsMangaUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetStatisticsMangaUuid200Response>("/statistics/manga/{uuid}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsMangaUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetStatisticsMangaUuid200Response</returns>
        public async System.Threading.Tasks.Task<GetStatisticsMangaUuid200Response> GetStatisticsMangaUuidAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            MangaDex.Client.ApiResponse<GetStatisticsMangaUuid200Response> localVarResponse = await GetStatisticsMangaUuidWithHttpInfoAsync(uuid, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get statistics about given Manga 
        /// </summary>
        /// <exception cref="MangaDex.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="uuid"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetStatisticsMangaUuid200Response)</returns>
        public async System.Threading.Tasks.Task<MangaDex.Client.ApiResponse<GetStatisticsMangaUuid200Response>> GetStatisticsMangaUuidWithHttpInfoAsync(Guid uuid, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            MangaDex.Client.RequestOptions localVarRequestOptions = new MangaDex.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MangaDex.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MangaDex.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("uuid", MangaDex.Client.ClientUtils.ParameterToString(uuid)); // path parameter

            localVarRequestOptions.Operation = "StatisticsApi.GetStatisticsMangaUuid";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (Bearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetStatisticsMangaUuid200Response>("/statistics/manga/{uuid}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetStatisticsMangaUuid", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
